version: "3"
services:
  wvpRedis:
    image: redis:6.2-rc3-alpine3.13
    restart: always
    environment:
      TZ: ${TZ}
    ports:
      - 63790:6379
    volumes:
      - ${REDIS_DATA}:/data
      - ${REDIS_LOG}:/logs
    command: redis-server --port 6379 --requirepass ${REDIS_PASSWORD}  --appendonly yes
  wvpMysql:
    image: mysql:8 # 指定镜像和版本
    restart: always # 指定开机重启
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      SQL_MODE: "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql:rw # 挂载数据目录
  wvp:
    image:
    restart: always
    environment:
      TZ: ${TZ}
      WVP_DOMAIN: ${WVP_DOMAIN}
      WVP_ID: ${WVP_ID}
      WVP_PASSWORD: ${WVP_PASSWORD}
      WVP_IP: ${WVP_IP}
      SIP_IP: ${SIP_IP}
      MEDIA_IP: ${MEDIA_IP}
      WVP_PORT: ${WVP_PORT}
      WVP_DB_PATH: ${WVP_DB_PATH}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: wvpRedis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PWD: ${REDIS_PASSWORD}
      MEDIA_PORT: ${MEDIA_PORT}
      ASSIST_PORT: ${ASSIST_PORT}
      RECORD_PATH: ${RECORD_PATH}
      STREAM_HOST: ${STREAM_HOST}
      DRUID_USER: ${DRUID_USER}
      DRUID_PASS: ${DRUID_PASS}
    ports:
      - 30000-30500:30000-30500/udp
      - 30000-30500:30000-30500/tcp
      - 5060:5060
      - 5060:5060/udp
      # 按需调整宿主机的端口
      - ${MEDIA_PORT}:${MEDIA_PORT}
      - ${WVP_PORT}:${WVP_PORT}
      # - 554:554
      # - 1935:1935
    expose:
      - ${MEDIA_PORT}
      - ${WVP_PORT}
    volumes:
      - ./record:/media/record:rw # 录像保存目录
      - ./wvp/config/run.sh:/opt/wvp/run.sh
      - ./wvp/config/application.yml:/opt/wvp/config/application.yml
      - ./wvp/config/application.assist.yml:/opt/assist/config/application.yml
      - ./wvp/config/logback-spring-local.xml:/opt/assist/config/logback-spring-local.xml
      - ./wvp/config/config.ini:/config/config.ini
      - ./logs/assist:/opt/assist/logs # 保存assist日志
      - ./logs/wvp:/opt/wvp/logs # 保存wvp日志
      - ./logs/media:/opt/media/log # 保存zlm日志
    depends_on:
      - wvpMysql
      - wvpRedis
